name: vivadoo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.4.0+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  dropdown_button2: ^2.3.9
  http: ^1.2.1
  sticky_headers: ^0.3.0+2
  hive_flutter:
  path_provider: ^2.1.2
  hive_generator:
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_sliders: ^25.1.40
  social_share: ^2.3.1
  go_router: ^14.1.4
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  dio: ^5.4.2+1
  image_gallery_saver: ^2.0.3
  webview_flutter: ^4.7.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.5
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.0.1
  app_tracking_transparency: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/nav_bar_icons/
    - assets/icons/filter_search/
    - assets/icons/post_details_icons/
    - assets/icons/user_ads_icons/
    - assets/icons/filter_sorting/
    - assets/icons/auth/
